// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmYEHlqy32vchZhnm0VifCAQ47Xa2lshU',
    appId: '1:85490416984:web:3cdc12fcae796e17ae392d',
    messagingSenderId: '85490416984',
    projectId: 'revalida-cards',
    authDomain: 'revalida-cards.firebaseapp.com',
    storageBucket: 'revalida-cards.firebasestorage.app',
    measurementId: 'G-31KWW2MMMV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv7lKrRe3YW7Ht4NR9I3YE7wrcycgrHHg',
    appId: '1:85490416984:android:95125e4d63cab2e2ae392d',
    messagingSenderId: '85490416984',
    projectId: 'revalida-cards',
    storageBucket: 'revalida-cards.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxCdPH51t-1ndLJVy-skgpq0ZdfK6lfvE',
    appId: '1:85490416984:ios:7aa3b9675bd8eddeae392d',
    messagingSenderId: '85490416984',
    projectId: 'revalida-cards',
    storageBucket: 'revalida-cards.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxCdPH51t-1ndLJVy-skgpq0ZdfK6lfvE',
    appId: '1:85490416984:ios:7aa3b9675bd8eddeae392d',
    messagingSenderId: '85490416984',
    projectId: 'revalida-cards',
    storageBucket: 'revalida-cards.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmYEHlqy32vchZhnm0VifCAQ47Xa2lshU',
    appId: '1:85490416984:web:278cfd93f65b9b4bae392d',
    messagingSenderId: '85490416984',
    projectId: 'revalida-cards',
    authDomain: 'revalida-cards.firebaseapp.com',
    storageBucket: 'revalida-cards.firebasestorage.app',
    measurementId: 'G-26QX2KRX84',
  );
}
